version: '3.8'
services:
  jenkins:
    image: ${IMAGE}
    container_name: ${NAME}
    env_file: .env
    environment:
      - USE_SECURITY=${USE_SECURITY}
      - OAUTH_ID=${OAUTH_ID}
      - OAUTH_SECRET=${OAUTH_SECRET}
      - JENKINS_API_USER=${JENKINS_API_USER}
      - JENKINS_API_PASSWORD=${JENKINS_API_PASSWORD}
      - DOCKER_GID=${DOCKER_GID}
    volumes:
      - ${JENKINS_HOME}/jobs:/var/jenkins_home/jobs
      - ${JENKINS_HOME}/.netrc:/var/jenkins_home/.netrc
      - ${JENKINS_HOME}/.netrc:/var/jenkins_home/.secrets
  haproxy:
   image: haproxy:2.9.4
   container_name: ${NAME}-haproxy
   ports:
     - "8080:8080"
   volumes:
     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
