version: '3.8'
services:
  jenkins:
    image: ${IMAGE}
    container_name: ${NAME}
    env_file: jenkins-container.env
    volumes:
      - ${JENKINS_HOME}/jobs:/var/jenkins_home/jobs
      - ${JENKINS_HOME}/.netrc:/var/jenkins_home/.netrc
      - ${JENKINS_HOME}/.netrc:/var/jenkins_home/.secrets
  haproxy:
   image: haproxy:2.9.4
   container_name: ${NAME}-haproxy
   ports:
     - "8080:8080"
   volumes:
     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
