version: '3.8'
services:
  jenkins:
    image: ${IMAGE}
    container_name: ${NAME}
    env_file: jenkins-container.env
    volumes:
      - ${JENKINS_HOME}/jobs:/var/jenkins_home/jobs
      - ${JENKINS_HOME}/.netrc:/var/jenkins_home/.netrc
      - ${JENKINS_HOME}/.secrets:/var/jenkins_home/.secrets
  haproxy:
   image: haproxy:2.9.4
   container_name: ${NAME}-haproxy
   env_file: jenkins-container.env
   ports:
     - "8080:8080"
   volumes:
     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
     - ./haproxy/lua:/usr/local/etc/haproxy/lua:ro
     - ./haproxy/403.http:/usr/local/etc/haproxy/errors/403.http:ro
