version: '3.8'
services:
  jenkins:
    image: ${IMAGE}
    container_name: ${NAME}
    env_file: jenkins-container.env
    volumes:
      - ${JENKINS_HOME}/jobs:/var/jenkins_home/jobs
      - ${JENKINS_HOME}/.netrc:/var/jenkins_home/.netrc
      - ${JENKINS_HOME}/.secrets:/var/jenkins_home/.secrets
  haproxy:
   image: haproxy:2.9.4
   container_name: ${NAME}-haproxy
   env_file: jenkins-container.env
   ports:
     - "80:8080"
     - "443:8443"
   volumes:
     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
     - ./haproxy/lua:/usr/local/etc/haproxy/lua:ro
     - ./haproxy/403.http:/usr/local/etc/haproxy/errors/403.http:ro
     - ${GERRIT_CI_PEM}:/usr/local/etc/haproxy/ssl/certs/gerrit-ci.pem
  nginx:
   image: nginx:stable-alpine3.17-slim
   container_name: ${NAME}-nginx
   ports:
     - "8081:80"
   volumes:
     - ${JENKINS_CSS_PATH}:/usr/share/nginx/html/:ro
  cache:
   image: buchgr/bazel-remote-cache:v2.4.4
   container_name: ${NAME}-cache
   command: --max_size ${BAZEL_CACHE_SIZE_GB}
   ports:
     - "8082:8080"
     - "9092:9092"
   volumes:
     - ${BAZEL_CACHE_PATH}:/data
