- project:
    name: metrics-reporter-prometheus
    jobs:
      - 'plugin-{name}-bazel-{branch}':
          branch:
            - master
      - 'plugin-{name}-bazel-{branch}-{gerrit-branch}':
          branch:
            - master
          gerrit-branch:
            - stable-3.5
            - stable-3.4
            - stable-3.3
