- project:
    name: server-config
    jobs:
      - 'plugin-{name}-{branch}':
          branch:
            - stable-2.13
      - 'plugin-{name}-bazel-{branch}':
          branch:
            - master
